### ISSUE TITLE
Add the option to delete a round

### ISSUE THREAD

**Issue by yatiac** [biharygergo/card-estimator#149]
![image](https://github.com/biharygergo/card-estimator/assets/1914303/949fe357-3354-4208-99f8-1bc0ef6c9568)

**Comment by biharygergo** [comment]
Hey @yatiac, thanks for opening this issue (and sorry for not noticing it earlier)! This has been long overdue, thanks for pointing it out. :) 

I've added the feature in #150, please let me know whether this works for you.

Have a great day!

**Comment by yatiac** [comment]
it works amazingly, I was trying to build it myself, but my knowledge was limited on this one. Thanks for the quick turnaround.
