### ISSUE TITLE
problems wich deployment

### ISSUE THREAD

**Issue by armandoytriago** [biharygergo/card-estimator#151]
i have problems wich deployment
<img width="1165" alt="image" src="https://github.com/biharygergo/card-estimator/assets/131711893/15ed3dad-70e0-4e6c-b39e-65d6cdfa2d6c">

**Comment by biharygergo** [comment]
Hey @armandoytriago,

Could you open your Developer Tools and check the Console for any potential error messages? The app should generally show what error occured, but in this case something has gone very wrong. Could you check whether there is an issue with your network/firewall settings as well? 

Hope we can find the solution soon!
