### ISSUE TITLE
Add possibility to use more cards

### ISSUE THREAD

**Issue by tt1991** [biharygergo/card-estimator#80]
The maximum limit for cards is 6 at this moment. A higher limit (like 10) would be appreciated for som use-cases like bigger projects.

**Comment by biharygergo** [comment]
Hey there, thanks for raising this issue! I'll look into modifying the limit, I believe it can go higher, though it might cause some UI inconsistencies (flowing out of the viewport, or too much scrolling on mobile) if it's misused. What kind of card set do you use (e.g.: numbers, letters, words)?

**Comment by tt1991** [comment]
We would like to use fibonacci card set, but adding cards to reach at maximum 100. We would like to use this app for estimate bigger project. In the first round it can be bigger number, then we would separate them in smaller issues. So for us 10 is the absolute maximum number of cards, we will use.

**Comment by biharygergo** [comment]
I've added this feature, could you check it now and let me know if it's good? :)

**Comment by tt1991** [comment]
Thanks, for the quick action. It works fine, I can create custom set with more than 6 card without a problem. :) However the UI during the set create process only shows 6 card at maximum as a preview and the warning message looks a bit out of place (maybe an extra margin to separate it from the other text). These are just UX stuff, it is not problem to me, just as a feedback.

**Comment by biharygergo** [comment]
Thanks for raising this, I've improved the UI a bit now, so the preview cards will show between 6 and 10 when a longer input is given. Also, I've removed the warning message, it does not add too much value. 

Also, thanks for opening this first issue! 🏆  Don't hesitate to open more if you think something could be improved or seems broken. Cheers!
